src/Bundle/TournamentBundle/Entity/Round.php
<?php

namespace Bundle\TournamentBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Round
 *
 * @ORM\Table(name="round")
 * @ORM\Entity
 */
class Round
{

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="number", type="string", length=10)
     */
    private $number;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="estimatedDate", type="datetime", nullable=true)
     */
    private $estimatedDate;

    /**
     *
     * @ORM\OneToMany(targetEntity="FootballMatch", mappedBy="round",cascade={"persist","remove"})
     */
    private $matches;

    /**
     * @ORM\ManyToOne(targetEntity="Tournament", inversedBy="rounds")
     * @ORM\JoinColumn(name="tournament", referencedColumnName="id", nullable=false)
     */
    private $tournament;

    /**
     * @ORM\ManyToOne(targetEntity="RoundStatus")
     * @ORM\JoinColumn(name="round_status", referencedColumnName="id")
     */
    private $roundStatus;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->matches = new \Doctrine\Common\Collections\ArrayCollection();
    }

    public function __toString()
    {
        return "Fecha " . $this->getNumber() . ", " . $this->getTournament();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set number
     *
     * @param string $number
     * @return Round
     */
    public function setNumber($number)
    {
        $this->number = $number;

        return $this;
    }

    /**
     * Get number
     *
     * @return string 
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * Set estimatedDate
     *
     * @param \DateTime $estimatedDate
     * @return Round
     */
    public function setEstimatedDate($estimatedDate)
    {
        $this->estimatedDate = $estimatedDate;

        return $this;
    }

    /**
     * Get estimatedDate
     *
     * @return \DateTime 
     */
    public function getEstimatedDate()
    {
        return $this->estimatedDate;
    }

    /**
     * Set matches
     *
     * @param array $matches
     * @return Round
     */
    public function setMatches($matches)
    {
        $this->matches = $matches;

        return $this;
    }

    /**
     * Get matches
     *
     * @return array 
     */
    public function getMatches()
    {
        return $this->matches;
    }

    /**
     * Add matches
     *
     * @param \Bundle\TournamentBundle\Entity\FootballMatch $matches
     * @return Round
     */
    public function addMatch(\Bundle\TournamentBundle\Entity\FootballMatch $matches)
    {
        $this->matches[] = $matches;

        return $this;
    }

    /**
     * Remove matches
     *
     * @param \Bundle\TournamentBundle\Entity\FootballMatch $matches
     */
    public function removeMatch(\Bundle\TournamentBundle\Entity\FootballMatch $matches)
    {
        $this->matches->removeElement($matches);
    }

    /**
     * Set tournament
     *
     * @param \Bundle\TournamentBundle\Entity\Tournament $tournament
     * @return Round
     */
    public function setTournament(\Bundle\TournamentBundle\Entity\Tournament $tournament = null)
    {
        $this->tournament = $tournament;

        return $this;
    }

    /**
     * Get tournament
     *
     * @return \Bundle\TournamentBundle\Entity\Tournament 
     */
    public function getTournament()
    {
        return $this->tournament;
    }

    /**
     * Set roundStatus
     *
     * @param \Bundle\TournamentBundle\Entity\RoundStatus $roundStatus
     *
     * @return Round
     */
    public function setStatus(\Bundle\TournamentBundle\Entity\RoundStatus $roundStatus = null)
    {
        $this->roundStatus = $roundStatus;

        return $this;
    }

    /**
     * Get roundStatus
     *
     * @return \Bundle\TournamentBundle\Entity\RoundStatus
     */
    public function getStatus()
    {
        return $this->roundStatus;
    }

    /**
     * Set roundStatus
     *
     * @param \Bundle\TournamentBundle\Entity\RoundStatus $roundStatus
     *
     * @return Round
     */
    public function setRoundStatus(\Bundle\TournamentBundle\Entity\RoundStatus $roundStatus = null)
    {
        $this->roundStatus = $roundStatus;

        return $this;
    }

    /**
     * Get roundStatus
     *
     * @return \Bundle\TournamentBundle\Entity\RoundStatus
     */
    public function getRoundStatus()
    {
        return $this->roundStatus;
    }

}

src/Bundle/TournamentBundle/Entity/TournamentType.php
<?php

namespace Bundle\TournamentBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * TournamentType
 *
 * @ORM\Table(name="tournament_type")
 * @ORM\Entity
 */
class TournamentType
{

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=25)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     */
    private $description;

    public function __toString()
    {
        return $this->getTitle();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return TournamentType
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return TournamentType
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

}

src/Bundle/TournamentBundle/Controller/TournamentController.php
<?php

/**
 * Created by PhpStorm.
 * User: gonetil
 * Date: 23/04/15
 * Time: 19:20
 */

namespace Bundle\TournamentBundle\Controller;

use Sonata\AdminBundle\Controller\CRUDController as Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Bundle\TournamentBundle\Common\MatchUtils;

class TournamentController extends Controller
{

    public function autogenerateFixtureAction($id)
    {
        $tournament = $this->admin->getObject($id);

        if (!$tournament) {
            throw new NotFoundHttpException(sprintf('No se pudo encontrar el Torneo con id : %s', $id));
        }

        if ($tournament->getTeams()->count() < 2) {
            $this->addFlash('sonata_flash_error', 'El torneo debe tener al menos 2 equipos registrados.');
        } else {
            $this->get('tournament.manager.fixture')->autogenerateFixture($tournament);
            $this->admin->update($tournament);
            $this->addFlash('sonata_flash_success', 'Fixture preparado satisfactoriamente');
        }

        return new RedirectResponse($this->admin->generateUrl('show', array('id' => $tournament->getId())));
    }

    /**
     * @Template()
     */
    public function positionsTableAction($id)
    {
        $admin_pool = $this->get('sonata.admin.pool');

        $tournament = $this->admin->getObject($id);
        if (!$tournament) {
            throw new NotFoundHttpException(sprintf('No se pudo encontrar el Torneo con id : %s', $id));
        }

        $positions = array();
        $teams = array();
        foreach ($tournament->getTeamsParticipation() as $teamInTournament) {
            $positions[$teamInTournament->getId()] = array('pj' => 0, 'pg' => 0, 'pe' => 0, 'pp' => 0, 'gf' => 0, 'gc' => 0, 'pts' => 0);
            $teams[$teamInTournament->getId()] = $teamInTournament;
        }

        foreach ($tournament->getRounds() as $round) {
            foreach ($round->getMatches() as $match) {
                if (MatchUtils::isMatchEnded($match)) {
                    $positions[$match->getLocal()->getId()]['pj'] ++;
                    $positions[$match->getVisitor()->getId()]['pj'] ++;

                    if (MatchUtils::isLocalWinner($match)) {
                        $positions[$match->getLocal()->getId()]['pg'] ++;
                        $positions[$match->getVisitor()->getId()]['pp'] ++;
                    } elseif (MatchUtils::isVisitorWinner($match)) {
                        $positions[$match->getVisitor()->getId()]['pg'] ++;
                        $positions[$match->getLocal()->getId()]['pp'] ++;
                    } else {
                        $positions[$match->getVisitor()->getId()]['pe'] ++;
                        $positions[$match->getLocal()->getId()]['pe'] ++;
                    }

                    $positions[$match->getVisitor()->getId()]['gf'] += $match->getVisitorGoals();
                    $positions[$match->getLocal()->getId()]['gf'] += $match->getLocalGoals();

                    $positions[$match->getVisitor()->getId()]['gc'] += $match->getLocalGoals();
                    $positions[$match->getLocal()->getId()]['gc'] += $match->getVisitorGoals();

                    $positions[$match->getVisitor()->getId()]['pts'] += MatchUtils::visitorPoints($match);
                    $positions[$match->getLocal()->getId()]['pts'] += MatchUtils::localPoints($match);
                }
            }
        }

        uasort($positions, function ($a, $b) {
            if ($a['pts'] === $b['pts']) {
                return 0;
            }
            return ($a['pts'] > $b['pts']) ? -1 : 1;
        });

        foreach ($positions as $key => $value) {
            $teamsInTournament[] = $teams[$key];
        }

        return array(
            'admin_pool' => $admin_pool,
            'teamsInTournament' => $teamsInTournament,
            'positions' => $positions
        );
    }

    public function inscriptionsDiscountAction($id)
    {
        $tournament = $this->admin->getObject($id);

        if (!$tournament) {
            throw new NotFoundHttpException(sprintf('No se pudo encontrar el Torneo con id : %s', $id));
        }

        $currentAccountManager = $this->get('tournament.manager.current_account');

        foreach ($tournament->getTeams() as $team) {
            $currentAccountManager->discountTournamentInscription($team, $tournament);
        }

        return new RedirectResponse($this->admin->generateUrl('show', array('id' => $tournament->getId())));
    }

    /**
     * @Template()
     */
    public function topScorersAction($id)
    {
        $admin_pool = $this->get('sonata.admin.pool');

        $tournament = $this->admin->getObject($id);
        if (!$tournament) {
            throw new NotFoundHttpException(sprintf('No se pudo encontrar el Torneo con id : %s', $id));
        }

        $qb = $this->getDoctrine()->getManager()
                ->getRepository('TournamentBundle:PlayerParticipation')
                ->createQueryBuilder('pp');

        $qb = $qb->select('pp,p,tmp,tt')
                ->innerJoin('pp.teamMatchParticipation', 'tmp')
                ->innerJoin('pp.player', 'p')
                ->innerJoin('tmp.teamInTournament', 'tt')
                ->innerJoin('tmp.playedFootballMatch', 'pfm')
                ->leftJoin('pfm.footballMatch', 'fm')
                ->leftJoin('fm.round', 'r')
                ->leftJoin('r.tournament', 'tournament')
                ->where('tournament = :tournament')
                ->setParameter('tournament', $tournament)
        ;

        $scorers = $qb->getQuery()->getResult();

        return array(
            'admin_pool' => $admin_pool,
            'scorers' => $scorers
        );
    }

}

src/Bundle/TournamentBundle/Resources/views/Tournament/edit.html.twig
{% extends 'SonataAdminBundle:CRUD:base_edit.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
        $(document).ready(function () {
            field = $('#{{ admin.uniqid ~ "_generateFixture" }}');
            field.on('ifChecked', function () {
                if (!confirm('Al generar el nuevo fixture, se eliminará el fixture actual para este torneo.')) {
                    var cual = this;
                    setTimeout(function () {
                        $(cual).iCheck('uncheck');
                    }, 1);
                }
            });
        });
    </script>
{% endblock %}

src/Bundle/TournamentBundle/Resources/views/Tournament/list__action_autogenerateFixture.html.twig
<a id="autogenerate_fixture" class="btn btn-default btn-sm" href="{{ admin.generateObjectUrl('autogenerateFixture', object) }}">
    <span class="glyphicon glyphicon-calendar"></span> 
    {{ 'Generar fixture' | trans }}
</a>

src/Bundle/TournamentBundle/Resources/views/Tournament/new.html.twig
{% extends 'SonataAdminBundle:CRUD:base_new.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
        $(document).ready(function () {
            field = $('#{{ admin.uniqid ~ "_generateFixture" }}');
            field.on('ifChecked', function () {
                if (!confirm('Al generar el nuevo fixture, se eliminará el fixture actual para este torneo.')) {
                    var cual = this;
                    setTimeout(function () {
                        $(cual).iCheck('uncheck');
                    }, 1);
                }
            });
        });
    </script>
{% endblock %}

src/Bundle/TournamentBundle/Resources/views/Tournament/positionsTable.html.twig
{% extends 'SonataAdminBundle::standard_layout.html.twig' %}

{% block sonata_admin_content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h1>Tabla de posiciónes</h1>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Equipo</th>
                            <th>PJ</th>
                            <th>PG</th>
                            <th>PE</th>
                            <th>PP</th>
                            <th>GF</th>
                            <th>GC</th>
                            <th>Pts</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for tt in teamsInTournament %}
                            <tr>
                                <td>{{ tt.team.name }}</td>
                                <td>{{ positions[tt.id]['pj'] }}</td>
                                <td>{{ positions[tt.id]['pg'] }}</td>
                                <td>{{ positions[tt.id]['pe'] }}</td>
                                <td>{{ positions[tt.id]['pp'] }}</td>
                                <td>{{ positions[tt.id]['gf'] }}</td>
                                <td>{{ positions[tt.id]['gc'] }}</td>
                                <td>{{ positions[tt.id]['pts'] }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div>
{% endblock %}

src/Bundle/TournamentBundle/Resources/views/Tournament/show.html.twig
{% extends 'SonataAdminBundle:CRUD:base_show.html.twig' %}

{% block actions %}

    <li>{% include 'SonataAdminBundle:Button:edit_button.html.twig' %}</li>
    <li>{% include 'SonataAdminBundle:Button:history_button.html.twig' %}</li>
    <li>{% include 'SonataAdminBundle:Button:list_button.html.twig' %}</li>
    <li>{% include 'SonataAdminBundle:Button:create_button.html.twig' %}</li>
    <li>{% include 'TournamentBundle:Button:autogenerate_fixture.html.twig' %}</li>
    <li>{% include 'TournamentBundle:Button:inscriptions_discount.html.twig' %}</li>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
        $(document).ready(function () {
            field = $('#autogenerate_fixture');
            field.on('click', function () {
                $.ajax({
                });
                return confirm('Al generar el nuevo fixture, se eliminará el fixture actual para este torneo.');
            });
        });
    </script>
{% endblock %}

{% block show %}

    {{ sonata_block_render_event('sonata.admin.show.top', { 'admin': admin, 'object': object }) }}

    <div class="row">
        <div class="col-md-12">
            <h1>Torneo {{ object.name }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-4">
                    <dl class="dl-horizontal">
                        <dt>Tipo</dt>
                        <dd>{{ object.type }}</dd>

                        <dt>Estado</dt>
                        <dd>{{ object.status }}</dd>

                        <dt>Fecha de Inicio</dt>
                        <dd>{{ object.dateBegin | date('d/m/Y ') }}</dd>

                        <dt>Fecha de Fin</dt>
                        <dd>{{ object.dateEnd| date('d/m/Y') }}</dd>
                    </dl>
                </div>
                <div class="col-md-4">
                    <dl class="dl-horizontal">
                        <dt>Registro de participantes abierto?</dt>
                        <dd>{{ object.isRegistrationOpen }}</dd>

                        <dt>Costo de inscripcion</dt>
                        <dd>{{ object.inscriptionCostPerTeam }}</dd>

                        <dt>Costo por equipo por partido</dt>
                        <dd>{{ object.matchCostPerTeam }}</dd>
                    </dl>
                </div>
                <div class="col-md-4"></div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <h2>Equipos participantes</h2>
                    <table class="table table-condensed">
                        <thead>
                            <tr>
                                <td colspan="2">Equipo</td>
                            </tr>
                        </thead>
                        <tbody>
                            {% for team in object.teams %}
                                <tr>
                                    <td>
                                        <div class="team-flag-tiny pull-left">
                                            <img src="{{ team.flag }}"/>
                                        </div>
                                    </td>
                                    <td>
                                        <a href="{{ path('tournament_team_show',{'id': team.id }) }}">{{ team.name }}</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="col-md-6">
                    <h2>Fixture</h2>
                    <div class="row">
                        <div class="col-md-10">
                            <div class="panel-group" id="fixture" role="tablist" aria-multiselectable="true">
                                {% for round in object.rounds %}
                                    <div class="panel panel-default">
                                        <div class="panel-heading" role="tab" id="heading_collapse_round_{{ round.id }}">
                                            <h4 class="panel-title">
                                                <a class="pull-right" href="{{ path('tournament_round_show', { 'id': round.id}) }}"><i class="fa fa-edit"></i>    </a>
                                                <a role="button" data-toggle="collapse" data-parent="#fixture" href="#collapse_round_{{ round.id }}" aria-expanded="false" aria-controls="collapse_round_{{ round.id }}">
                                                    {{ round }}
                                                </a>
                                            </h4>
                                        </div>
                                        <div id="collapse_round_{{ round.id }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading_collapse_round_{{ round.id }}">
                                            <div class="panel-body">
                                                {% for match in round.matches %}
                                                    <p>{{ match.orderInRound }} : {{ match.local }} vs {{ match.visitor }}
                                                        ({{ match.court }} 
                                                        {% if match.dateAndTime is not null %}
                                                            {{ match.dateAndTime | date('d/m/Y H:i') }} hs
                                                        {% endif %}
                                                        )
                                                    </p>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <script>
                        $("a.collapsed").attr("aria-expanded", "false");
                    </script>
                </div>
            </div>
        </div>
    </div>

    {{ sonata_block_render_event('sonata.admin.show.bottom', { 'admin': admin, 'object': object }) }}

{% endblock %}

src/Bundle/TournamentBundle/Resources/views/Tournament/topScorers.html.twig
{% extends 'SonataAdminBundle::standard_layout.html.twig' %}

{% block sonata_admin_content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h1>Goleadores</h1>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Jugador</th>
                            <th>Equipo</th>
                            <th>Goles</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for p in scorers %}
                            <tr>
                                <td>{{ p.player }}</td>
                                <td>{{ p.teamMatchParticipation.teamInTournament }}</td>
                                <td>{{ p.goals }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div>
{% endblock %}